server:
  port: 8080

spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "*"
            allowed-methods: "GET,POST,PUT,DELETE"
            allowed-headers: "*"
      routes:
        - id: product-service
          uri: http://product-service:8080
          predicates:
            - Path=/products/**, /api/v1/products/**
        - id: inventory-service
          uri: http://inventory-service:8080
          predicates:
            - Path=/inventory/**, /api/v1/stores/**
        - id: reporting-service
          uri: http://reporting-service:8080
          predicates:
            - Path=/reports/**, /api/v1/reports/**
        - id: customer-service
          uri: http://customer-service:8080
          predicates:
            - Path=/customers/**, /api/v1/customers/**
        - id: cart-service
          uri: http://cart-service:8080
          predicates:
            - Path=/carts/**, /api/v1/carts/**
        - id: order-service
          uri: http://order-service:8080
          predicates:
            - Path=/orders/**, /api/v1/orders/**
        - id: saga-orchestrator
          uri: http://saga-orchestrator:8080
          predicates:
            - Path=/api/v1/sagas/**
          filters:
            - StripPrefix=0 