@startuml
actor Client
participant "API Gateway\nlocalhost:8080" as Gateway
participant "Product Service" as ProductService
database "PostgreSQL" as DB

Client -> Gateway : GET /api/v1/products
Gateway -> ProductService : GET /api/v1/products
ProductService -> DB : SELECT * FROM produits
DB --> ProductService : Liste des produits
ProductService --> Gateway : Réponse JSON avec liste des produits
Gateway --> Client : Réponse avec liste des produits
@enduml